### ISSUE TITLE
BVH retarget explanation

### ISSUE THREAD

**Issue by WojtekPachowiak** [beemsoft/webxr-handtracking-playground#1]
Hi! 
I saw you mentioned that you succeeded in retargeting BVH:
https://discourse.threejs.org/t/bvh-animations-feedback/16081/19

I'm struggling myself and would love to ask you some questions! 

I've taken a look at the /src/demo/dance example and have following questions:
- are you using a custom `SkeletonUtils.ts` (i.e. you modified, for example, the `retarget` function)? Or is it the official unmodified one?
- do you still have the `models/gltf/Xbot.glb` and `models/bvh/Samy.bvh` ? I would like to inspect their bone hierarchies.
- in [this line](https://github.com/beemsoft/webxr-handtracking-playground/blob/f3c3fc74edaaefda7986db08492b1802ae5dbee2/src/demo/dance/src/scene/SceneManager.ts#L126) why are you retargeting every frame? isn't that wasteful and redundant?
- what does `this.player.children[0].children[1]` evaluate to? Is it a Skinned Mesh?

I have my own .bvh file and after being loaded by BVHLoader, I have the following skeleton:
![image](https://user-images.githubusercontent.com/50328147/234995585-7443a390-53da-4d2e-9d9f-2ec3fde2dc1b.png)
Isn't it weird that the "ENDSITE" bones get included? Blender, for example, completely ignores them. Did you have a similar problem? You know, after reading `SkeletonUtils`'s source code I see the `retarget` function depends heavily on the names of the bones. So it would make sense if these "ENDSITE"s would cause the retargeting to fail in my case.

Let me know if you would need some more info. from me! I can send you the .bvh file I'm using :)

**Comment by beemsoft** [comment]
Hi,

Thanks for your detailed questions!

* SkeletonUtils.ts is still doing mainly the same as the original version, but VrmSkeletonUtils.ts has been customized for VRM 
 models quite a bit. It can still be improved a lot, but at least it's working! 😄  
 Recently, I've added some BVH test demo's, each with its own retargetting code.
* Assets like GLB and BVH files have been moved to the public directory:
 See: [/public/src/demo/dance/model](https://github.com/beemsoft/webxr-handtracking-playground/tree/master/public/src/demo/dance/models)
* Retargeting for every frame is not that bad for WebXR. The BVH files I'm using for the Salsa demo's are perfect for 90 FPS rendering.
* `this.player.children[0].children[1]` is indeed referring to a Skinned Mesh. 
*  You are correct that the bone names are essential for the current retargeting implementation. 'ENDSITE' looks quite strange between the other bone names.

If you have problems matching your model with your BVH, you can send me both files.

Greetings,
Hans

**Comment by WojtekPachowiak** [comment]
I think I get how this works now! 

- It works on your bvh and glb from `dance` example. However I get the following artifact:
![image](https://user-images.githubusercontent.com/50328147/236634206-49562bb8-8f7d-40e7-8efe-0330ad01f34b.png)
![image](https://user-images.githubusercontent.com/50328147/236634208-5f748754-97b4-4d14-8d8c-42b11071b410.png)
As you can see, the mesh of the pelvis is constrained to world origin + it's super small :D
Why is that? Have you experiences this? 

in your demo pelvis and thighs are also weird:
![image](https://user-images.githubusercontent.com/50328147/236636600-7130a0f3-844c-4c0f-a6d2-7af300f90787.png)

compared to the model in Blender:
![image](https://user-images.githubusercontent.com/50328147/236636648-24fee281-8965-4df9-9b8e-01d7aea0cb6c.png)


- `SkeletonUtils.retarget(...)` - I thought this function needs to be invoked only once, but now I see why you call it every frame - otherwise it only retargets for one frame :D


WIll try later on my own bvh and model!

**Comment by beemsoft** [comment]
Hi,

It looks you are almost there! 😄 
For the pelvis, you need to check the mapping of the 'hip' bone. The model bone name should match with the BVH bone name.
As you've noticed, the retargetting for this XBot model has a strange issue with the legs. This issue doesn't occur in the other demo's with the VRM models.

Yes, retargetting should be done for every frame. Ideally, all the CPU-intensive calculations would not be performed in the UI thread. That could potentially be solved using a Worker thread.

Good luck with using your own BVH and model!
